language: java
sudo: false # faster builds

matrix:
  include:
    - os: linux
      sudo: required
      jdk: openjdk8

script:
  - ./script/package.sh

before_cache:
  - rm -rf  $HOME/.cache/**

cache:
  directories:
    - "$HOME/.cache"
